# Curso de python en udemy

## Numpy

#### Randn

In [ ]:
# Con números aleatorios pero positivos y negativos
import numpy as np
from numpy.random import randn

resultado = 0
contador = 0
for i in randn(10000):
    if i < 1 and i > -1:
        resultado += 1
    contador += 1
print(f'resultado es {resultado/contador}')

resultado es 0.6788


In [ ]:
# También se puede construir un vector
import numpy as np
vector = np.random.randn(5, 3)
vector

array([[-1.0568285 , -1.54388983,  0.77414571],
       [ 1.0194357 ,  0.223908  , -1.33580403],
       [-0.1943379 ,  0.42080044,  0.17852683],
       [-0.44506692, -0.36593675,  1.21114027],
       [-1.10066561,  0.08454591,  0.23246502]])

#### Rand

In [ ]:
# Solo números positivos
import numpy as np
vector = np.random.rand(5)
vector

array([0.10601463, 0.24487579, 0.43240822, 0.96009491, 0.19849926])

In [ ]:
# También podemos construir una matriz
import numpy as np
vector = np.random.rand(5,3)
vector

array([[0.48288093, 0.26207462, 0.65886966],
       [0.31527303, 0.5668327 , 0.84182064],
       [0.95935975, 0.20485767, 0.64546768],
       [0.44010923, 0.42732359, 0.0819377 ],
       [0.48195478, 0.21357189, 0.73343448]])

**diferencia array de numpy vs lista**

1 -  un array no puede tener distintos tipos de datos

2. – un array funciona como un objeto y se le pueden aplicar mas métodos que a una lista


In [ ]:
import numpy as np
lista = [235, 25, 2578]
a = np.array(lista)
a


array([ 235,   25, 2578])

In [ ]:
'''
si tenemos una variable con un array podemos crear una vista
de ese array con slicing asingnandole una variable, pero si
cambiamos el primer array el segundo tmbn se modificará,
pero podemos hacer un copy y ya no se modificará
'''

import numpy as np
letras = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i']
a = np.array(letras)
c = letras[0:2].copy()
a[0] = 'z'
a


array(['z', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i'], dtype='<U1')

In [ ]:
c

['a', 'b']

#### arange


In [ ]:
# para sacar un rango
listado = np.arange(10)
print(listado)


[0 1 2 3 4 5 6 7 8 9]


In [ ]:
import numpy as np
listado = np.arange(2, 10)
print(listado)


[2 3 4 5 6 7 8 9]


In [ ]:
listado = np.arange(2, 10, 2)
print(listado)


[2 4 6 8]


In [ ]:
import numpy as np
array = np.arange(0, 10)
array[0]

0

In [ ]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
array[-1]

9

In [ ]:
array[2:4]

array([2, 3])


Para sacar todo el array array[:]
Para sacar de la posición 5 hasta el final array[5:]
Para sacar de la posición inicial hasta la posición 4 array[:4]

#### Condiciones arange

In [ ]:
# numpy - seleccionar elementos de un array
import numpy as np
array = np.arange(0, 10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
condicion = array > 5
condicion

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [ ]:
array[condicion]

array([6, 7, 8, 9])

In [ ]:
array6 = array[condicion]
array6

array([6, 7, 8, 9])

In [ ]:
# mas rápido
array[array > 5]

array([6, 7, 8, 9])

#### Operaciones con arrays

In [ ]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
array + array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
array - array

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
array * 100

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [ ]:
array + 40

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [ ]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# aplicando funciones
np.sqrt(array)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [ ]:
np.max(array)

9

#### Linspace

In [ ]:
# genera 20 números entre 3 y 9
import numpy as np
vector = np.linspace(3,9,20)
print(vector)


[3.         3.31578947 3.63157895 3.94736842 4.26315789 4.57894737
 4.89473684 5.21052632 5.52631579 5.84210526 6.15789474 6.47368421
 6.78947368 7.10526316 7.42105263 7.73684211 8.05263158 8.36842105
 8.68421053 9.        ]


#### Randint

Sirve para genera aleatorios enteros, si le das un numero muestra entre 0 y ese numero  
Si le das dos, genera un numero entre el primero y el segundo(el segundo no se mostrará nunca)


In [ ]:
import numpy as np
np.random.randint(3,20)

3

## MATRICES

#### ZEROS ONES

In [ ]:

# Podemos crear un vector con zeros, con ones pondría 1 en lugar de 0
import numpy as np
vector = np.zeros((3, 6))
print(vector)


In [ ]:
# Con un numero parámetros generas un numero nuevo de enteros
import numpy as np
np.random.randint(3, 20, 5)

array([14,  4, 12,  6,  8])

In [ ]:
import numpy as np
vector = np.ones(3)
print(vector)


[1. 1. 1.]


#### EYE

In [ ]:
import numpy as np
vector = np.eye(6)
print(vector)


[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


### Indexación matrices
Para acceder a un valor de una matriz haremos a[2,3] para un valor,  
y para toda la fila haremos a[0,:]   
[:,0] para la columna

### Para construir una matriz

In [ ]:
import numpy as np
mis_datos = np.arange(0, 20)
print(mis_datos)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [ ]:
# con C los numeros se ordenan en horizontal
matr_1 = np.reshape(mis_datos, (5, 4), order = 'C')
matr_1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [ ]:
matr_1[2,1]

9

In [ ]:
# con F se ordenan en vertical
matr_2 = np.reshape(mis_datos,(5, 4), order='F')
matr_2

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [ ]:
matr_2[2,1]

7

In [ ]:
mis_datos

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
mis_datos.reshape(5, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

#### np.array()

In [ ]:
r1 = ["Soy", "muy", "feliz"]
r2 = ["Qué", "gran", "día"]
r3 = [1, 2, 3]
[r1, r2, r3]

[['Soy', 'muy', 'feliz'], ['Qué', 'gran', 'día'], [1, 2, 3]]

In [ ]:
np.array([r1, r2, r3])

array([['Soy', 'muy', 'feliz'],
       ['Qué', 'gran', 'día'],
       ['1', '2', '3']], dtype='<U11')

**numpy - indexacción en arrays de 2 o más dimensiones**
Array[0] sacaria la primera fila  
Para sacar las dos primeras filas, array[:2]  
Array[0][0] para sacar el primer elemento o array[0,0]  
Para sacar la primera columna sería array[:,0]  
Para las dos primeras columnas sería array[:,2]  


In [ ]:
import numpy as np
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
array[0]

array([1, 2, 3])