In [7]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns

vinos = pd.read_csv('C:/Users/SARAPC/Dropbox/phyton/machine learning/recursos/vino.csv')
vinos.head(10)


Alcohol  Malic acid   Ash  Alcalinity of ash  Magnesium  Total phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   
5    14.20        1.76  2.45               15.2      112.0           3.27   
6    14.39        1.87  2.45               14.6       96.0           2.50   
7    14.06        2.15  2.61               17.6      121.0           2.60   
8    14.83        1.64  2.17               14.0       97.0           2.80   
9    13.86        1.35  2.27               16.0       98.0           2.98   

   Flavanoids  Nonflavanoid phenols  Proanthocyanins  Color intensity   Hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   
5        3.39                  0.34             1.97             6.75  1.05   
6        2.52                  0.30             1.98             5.25  1.02   
7        2.51                  0.31             1.25             5.05  1.06   
8        2.98                  0.29             1.98             5.20  1.08   
9        3.15                  0.22             1.85             7.22  1.01   

   OD280/OD315 of diluted wines  Proline Wine Type  
0                          3.92   1065.0       One  
1                          3.40   1050.0       One  
2                          3.17   1185.0       One  
3                          3.45   1480.0       One  
4                          2.93    735.0       One  
5                          2.85   1450.0       One  
6                          3.58   1290.0       One  
7                          3.58   1295.0       One  
8                          2.85   1045.0       One  
9                          3.55   1045.0       One

In [9]:
vinos['Wine Type'].unique()

array(['One', 'Two', 'Three'], dtype=object)

In [15]:
# podemos saber la cantidad de cada tipo
vinos['Wine Type'].value_counts()

Wine Type
Two      71
One      59
Three    48
Name: count, dtype: int64

In [19]:
X = vinos.drop('Wine Type', axis=1)
y = vinos['Wine Type']
X



Alcohol  Malic acid   Ash  Alcalinity of ash  Magnesium  Total phenols  \
0      14.23        1.71  2.43               15.6      127.0           2.80   
1      13.20        1.78  2.14               11.2      100.0           2.65   
2      13.16        2.36  2.67               18.6      101.0           2.80   
3      14.37        1.95  2.50               16.8      113.0           3.85   
4      13.24        2.59  2.87               21.0      118.0           2.80   
..       ...         ...   ...                ...        ...            ...   
173    13.71        5.65  2.45               20.5       95.0           1.68   
174    13.40        3.91  2.48               23.0      102.0           1.80   
175    13.27        4.28  2.26               20.0      120.0           1.59   
176    13.17        2.59  2.37               20.0      120.0           1.65   
177    14.13        4.10  2.74               24.5       96.0           2.05   

     Flavanoids  Nonflavanoid phenols  Proanthocyanins  Color intensity   Hue  \
0          3.06                  0.28             2.29             5.64  1.04   
1          2.76                  0.26             1.28             4.38  1.05   
2          3.24                  0.30             2.81             5.68  1.03   
3          3.49                  0.24             2.18             7.80  0.86   
4          2.69                  0.39             1.82             4.32  1.04   
..          ...                   ...              ...              ...   ...   
173        0.61                  0.52             1.06             7.70  0.64   
174        0.75                  0.43             1.41             7.30  0.70   
175        0.69                  0.43             1.35            10.20  0.59   
176        0.68                  0.53             1.46             9.30  0.60   
177        0.76                  0.56             1.35             9.20  0.61   

     OD280/OD315 of diluted wines  Proline  
0                            3.92   1065.0  
1                            3.40   1050.0  
2                            3.17   1185.0  
3                            3.45   1480.0  
4                            2.93    735.0  
..                            ...      ...  
173                          1.74    740.0  
174                          1.56    750.0  
175                          1.56    835.0  
176                          1.62    840.0  
177                          1.60    560.0  

[178 rows x 13 columns]

In [21]:
y

0        One
1        One
2        One
3        One
4        One
       ...  
173    Three
174    Three
175    Three
176    Three
177    Three
Name: Wine Type, Length: 178, dtype: object

In [29]:
# dividimos en datos de entrenamiento y datos de prueba
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [31]:
from sklearn.tree import DecisionTreeClassifier

arbol = DecisionTreeClassifier()

#entrenamos el arbol
arbol.fit(X_train, y_train)

DecisionTreeClassifier()

In [33]:
# creamos una variable de predicciones
predicciones = arbol.predict(X_test)
predicciones

array(['Two', 'One', 'Three', 'One', 'Three', 'One', 'Three', 'Three',
       'One', 'One', 'One', 'Two', 'Two', 'Three', 'Two', 'One', 'Three',
       'One', 'Three', 'Three', 'Two', 'Two', 'Two', 'One', 'Two', 'Two',
       'One', 'Two', 'One', 'One', 'Three', 'Two', 'Two', 'Three', 'Two',
       'Three', 'Two', 'One', 'Two', 'One', 'One', 'Two', 'Two', 'Two',
       'Three', 'Two', 'Three', 'Two', 'Two', 'One', 'Three', 'Two',
       'One', 'One'], dtype=object)

In [35]:
#valores reales de las pruebas
y_test

103      Two
22       One
162    Three
6        One
137    Three
20       One
133    Three
134    Three
5        One
29       One
95       Two
125      Two
78       Two
154    Three
113      Two
53       One
131    Three
74       Two
155    Three
175    Three
119      Two
4        One
63       Two
51       One
96       Two
110      Two
10       One
97       Two
12       One
21       One
136    Three
116      Two
142    Three
70       Two
60       Two
157    Three
140    Three
15       One
126      Two
41       One
17       One
66       Two
124      Two
122      Two
138    Three
90       Two
160    Three
81       Two
109      Two
8        One
153    Three
150    Three
0        One
26       One
Name: Wine Type, dtype: object

In [37]:
#evaluar el modelo
#primero generar un informe para ver la precisión del modelo y por otro lado la matriz de confusión para ver cuantos falsos positivos y falsos negativos hay
from sklearn.metrics import classification_report, confusion_matrix


In [39]:
#esto nos evalua el modelo
print(classification_report(y_test, predicciones))

              precision    recall  f1-score   support

         One       0.89      0.94      0.91        17
       Three       0.93      0.81      0.87        16
         Two       0.82      0.86      0.84        21

    accuracy                           0.87        54
   macro avg       0.88      0.87      0.87        54
weighted avg       0.87      0.87      0.87        54



In [41]:
# positivos correctos y falsos positivos
print(confusion_matrix(y_test, predicciones))

[[16  0  1]
 [ 0 13  3]
 [ 2  1 18]]
