# Random Forest - Clasificación


In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

vinos = pd.read_csv('recursos/vino.csv')
vinos

Alcohol  Malic acid   Ash  Alcalinity of ash  Magnesium  Total phenols  \
0      14.23        1.71  2.43               15.6      127.0           2.80   
1      13.20        1.78  2.14               11.2      100.0           2.65   
2      13.16        2.36  2.67               18.6      101.0           2.80   
3      14.37        1.95  2.50               16.8      113.0           3.85   
4      13.24        2.59  2.87               21.0      118.0           2.80   
..       ...         ...   ...                ...        ...            ...   
173    13.71        5.65  2.45               20.5       95.0           1.68   
174    13.40        3.91  2.48               23.0      102.0           1.80   
175    13.27        4.28  2.26               20.0      120.0           1.59   
176    13.17        2.59  2.37               20.0      120.0           1.65   
177    14.13        4.10  2.74               24.5       96.0           2.05   

     Flavanoids  Nonflavanoid phenols  Proanthocyanins  Color intensity   Hue  \
0          3.06                  0.28             2.29             5.64  1.04   
1          2.76                  0.26             1.28             4.38  1.05   
2          3.24                  0.30             2.81             5.68  1.03   
3          3.49                  0.24             2.18             7.80  0.86   
4          2.69                  0.39             1.82             4.32  1.04   
..          ...                   ...              ...              ...   ...   
173        0.61                  0.52             1.06             7.70  0.64   
174        0.75                  0.43             1.41             7.30  0.70   
175        0.69                  0.43             1.35            10.20  0.59   
176        0.68                  0.53             1.46             9.30  0.60   
177        0.76                  0.56             1.35             9.20  0.61   

     OD280/OD315 of diluted wines  Proline Wine Type  
0                            3.92   1065.0       One  
1                            3.40   1050.0       One  
2                            3.17   1185.0       One  
3                            3.45   1480.0       One  
4                            2.93    735.0       One  
..                            ...      ...       ...  
173                          1.74    740.0     Three  
174                          1.56    750.0     Three  
175                          1.56    835.0     Three  
176                          1.62    840.0     Three  
177                          1.60    560.0     Three  

[178 rows x 14 columns]

In [4]:
# separar entre caracteristicas y tipo de vino
X = vinos.drop('Wine Type', axis=1)
y = vinos['Wine Type']



In [6]:
# dividimos en datos de entrenamiento y datos de prueba
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [8]:
# entrenar en modelo y hacer las predicciones

from sklearn.ensemble import RandomForestClassifier

In [10]:
# numero de estimadores 80
# creamos el modelo
random_forest = RandomForestClassifier(n_estimators=80)

# entrenamos el modelo
random_forest.fit(X_train, y_train)

RandomForestClassifier(n_estimators=80)

In [12]:
# realizamos las predicciones
predicciones = random_forest.predict(X_test)

In [14]:
# comparamos las predicciones con el y_test
predicciones

array(['Two', 'Two', 'One', 'One', 'Two', 'Two', 'One', 'Three', 'Three',
       'One', 'Two', 'Two', 'Three', 'Two', 'Three', 'Three', 'One',
       'Two', 'One', 'Three', 'Three', 'Two', 'One', 'Two', 'One', 'Two',
       'One', 'Two', 'Two', 'Three', 'Two', 'Two', 'Three', 'Three',
       'Two', 'One', 'Three', 'Two', 'Three', 'One', 'One', 'Two', 'Two',
       'One', 'One', 'Three', 'Two', 'Three', 'One', 'Three', 'Three',
       'Three', 'Two', 'Two'], dtype=object)

In [16]:
y_test

98       Two
106      Two
15       One
29       One
64       Two
70       Two
50       One
136    Three
133    Three
24       One
95       Two
60       Two
146    Three
129      Two
162    Three
168    Three
41       One
111      Two
23       One
152    Three
161    Three
93       Two
10       One
112      Two
38       One
121      Two
55       One
92       Two
62       Two
173    Three
71       Two
99       Two
174    Three
139    Three
68       Two
27       One
141    Three
102      Two
142    Three
33       One
6        One
59       Two
118      Two
56       One
35       One
177    Three
90       Two
158    Three
0        One
144    Three
150    Three
131    Three
126      Two
107      Two
Name: Wine Type, dtype: object

In [18]:
from sklearn.metrics import classification_report, confusion_matrix

In [22]:
print(classification_report(y_test, predicciones))
# el 1.00 significa que la precisión es del 100%

              precision    recall  f1-score   support

         One       1.00      1.00      1.00        15
       Three       1.00      1.00      1.00        17
         Two       1.00      1.00      1.00        22

    accuracy                           1.00        54
   macro avg       1.00      1.00      1.00        54
weighted avg       1.00      1.00      1.00        54



In [24]:
# imprimimos la matriz de confusion
print(confusion_matrix(y_test, predicciones))

[[15  0  0]
 [ 0 17  0]
 [ 0  0 22]]
